"""custom completions, which are not autogenerated.

remember:
[
    <trigger>: name\t<desc>: HISE
    <content>: string $1 or ${<id>:<change>}
]
"""
from textwrap import dedent

sn_list = [
    [
        'parseInt\treturn int from string: HISE',
        'parseInt(${1:var string})'
    ],
    [
        'callbacks mandatory\tmacro-snippet: HISE',
        dedent('''\
            function onNoteOn()
            {
            }
            function onNoteOff()
            {
            }
            function onController()
            {
            }
            function onTimer()
            {
            }
            function onControl(number, value)
            {
            }''')
    ],
    [
        'callback of control\tHISE',
        dedent('''\
            inline function on${1:name}Control(component, value)
            {
                ${2://code}
            };
            Content.getComponent("${1:name}").setControlCallback(on${1:name}Control);''')
    ],
    [
        'include\t Include source file: HISE',
        'include("${1:MyFile}.js");'
    ],
]
